# yarn repo
- apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present
  become: yes

#clean
- file: path=/etc/apt/sources.list.d/yarn.list state=absent

- apt_repository:
    repo: deb http://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: 'yarnpkg'
    update_cache: yes
  become: yes

- apt: 
    name: yarn
    state: latest
    install_recommends: no
  become: yes