
- name: Install fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
- shell: ~/.fzf/install

- name: Add docker apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release }} stable
    state: present
    update_cache: yes
  become: yes

- name: Upgrade minimal working tools ...
  apt: 
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
  - build-essential
  - tmux
  - curl
  - httpie
  - jq
  - git-flow
  - docker-ce
  - zip
  - unzip
  - vim
  - silversearcher-ag
  become: yes

- name: Allow docker for non root
  command: groupadd -f docker
  become: yes
- user: name={{ ansible_user }} groups=docker append=yes
  become: yes
  
- name: Install docker compose plugin
  apt:
    name: docker-compose-plugin
    install_recommends: yes
  become: yes

